### =======================================================================
### IMPORTACIÓN DE DATOS.
### =======================================================================

In [1]:
## IMPORTACIÓN GENERAL DE LIBRERIAS Y VISUALIZACIÓN DE DATOS (matplotlib y seaborn)
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as DT
import warnings
%matplotlib inline
warnings.filterwarnings('ignore')
plt.style.use('default') 
sns.set(style="whitegrid") 
plt.rcParams['figure.figsize'] = (15, 10)
# Load scikit's random forest classifier library
from sklearn.ensemble import RandomForestClassifier

In [2]:
training = ''
eventos = ''
dummies = ''
test = ''

In [3]:
## OBTENEMOS TODA LA INFORMACIÓN DEL SET DE ENTRENAMIENTO.
training = pd.read_csv('labels_training_set.csv', encoding = 'utf-8')
## OBTENEMOS TODA LA INFORMACIÓN DE LOS DIFERENTES EVENTOS.
eventos = pd.read_csv('events_up_to_01062018.csv', encoding = 'utf-8')
## OBTENEMOS TODA LA INFORMACIÓN A TESTEAR.
test = pd.read_csv('trocafone_kaggle_test.csv', encoding = 'utf-8')

In [4]:
## PASAMOS LAS COLUMNAS QUE TIENEN UNA CANTIDAD DE VALORES LIMITADA A UN TIPO CATEGORY
eventos['person'] = eventos['person'].astype('category')
eventos['event'] = eventos['event'].astype('category')
eventos['condition'] = eventos['condition'].astype('category')
eventos['storage'] = eventos['storage'].astype('category')
eventos['search_engine'] = eventos['search_engine'].astype('category')
eventos['channel'] = eventos['channel'].astype('category')
eventos['new_vs_returning'] = eventos['new_vs_returning'].astype('category')
eventos['device_type'] = eventos['device_type'].astype('category')
eventos['color'] = eventos['color'].astype('category')
eventos['region'] = eventos['region'].astype('category')
eventos['country'] = eventos['country'].astype('category')
eventos['operating_system_version'] = eventos['operating_system_version'].astype('category')
eventos['city'] = eventos['city'].astype('category')
eventos['browser_version'] = eventos['browser_version'].astype('category')
eventos['screen_resolution'] = eventos['screen_resolution'].astype('category')
eventos['model'] = eventos['model'].astype('category')
eventos['timestamp'] = pd.to_datetime(eventos['timestamp'], infer_datetime_format=True)

### =======================================================================
### ARMADO DE FEATURES.
### =======================================================================

In [5]:
## ORDENAMOS LOS DATOS ṔOR PERSONAS EN PRIMER LUGAR Y TIEMPO EN SEGUNDO.
eventos.sort_values(['person', 'timestamp'], ascending=[True, True], inplace=True)
## DIFERENCIAMOS EN TRES COLUMNAS DIFERENTES EL DIA, MES Y AÑO.
eventos['mes'] = eventos['timestamp'].dt.month
eventos['dia'] = eventos['timestamp'].dt.day
eventos['hora'] = eventos['timestamp'].dt.hour
## ARMAMOS UNA COLUMNA PARA EL DÍA DE LA SEMANA COMO NOMBRE.
eventos['diasemana'] = eventos['timestamp'].dt.weekday_name
## PONEMOS LOS NOMBRES DE MANERA MÁS PROLIJA PARA LOS GRÁFICOS.
eventos.loc[eventos.diasemana.str.contains('Monday', na=False), 'diasemana'] = 'lunes'
eventos.loc[eventos.diasemana.str.contains('Tuesday', na=False), 'diasemana'] = 'martes'
eventos.loc[eventos.diasemana.str.contains('Wednesday', na=False), 'diasemana'] = 'miercoles'
eventos.loc[eventos.diasemana.str.contains('Thursday', na=False), 'diasemana'] = 'jueves'
eventos.loc[eventos.diasemana.str.contains('Friday', na=False), 'diasemana'] = 'viernes'
eventos.loc[eventos.diasemana.str.contains('Saturday', na=False), 'diasemana'] = 'sabado'
eventos.loc[eventos.diasemana.str.contains('Sunday', na=False), 'diasemana'] = 'domingo'
# DEFINIMOS UNA LÓGICA PARA INDICAR SI EL DÍA EN QUE SE EJECUTA EL EVENTO ES FIN DE SEMANA.
eventos['finde'] = 0
eventos.loc[(eventos.diasemana.str.contains('DOM', na=False) | eventos.diasemana.str.contains('SAB', na=False)), 'finde'] = 1
# DEFINIMOS EL MES COMO NOMBRE PARA FACILITAR LAS COLUMNAS
eventos['mesMayus'] = ''
eventos.loc[eventos.mes == 1, 'mesMayus'] = 'enero'
eventos.loc[eventos.mes == 2, 'mesMayus'] = 'febrero'
eventos.loc[eventos.mes == 3, 'mesMayus'] = 'marzo'
eventos.loc[eventos.mes == 4, 'mesMayus'] = 'abril'
eventos.loc[eventos.mes == 5, 'mesMayus'] = 'mayo'
eventos.loc[eventos.mes == 6, 'mesMayus'] = 'junio'
eventos.loc[eventos.mes == 7, 'mesMayus'] = 'julio'
eventos.loc[eventos.mes == 8, 'mesMayus'] = 'agosto'
eventos.loc[eventos.mes == 9, 'mesMayus'] = 'septiembre'
eventos.loc[eventos.mes == 10, 'mesMayus'] = 'octubre'
eventos.loc[eventos.mes == 11, 'mesMayus'] = 'noviembre'
eventos.loc[eventos.mes == 12, 'mesMayus'] = 'diciembre'
# ARMAMOS UNA LÓGICA PARA SEGMENTAR LAS FRANJAS HORARIAS.
# MADRUGADA de 00 a 06
eventos['hora_madrugada'] = 0
eventos.loc[((eventos.hora > -1) & (eventos.hora < 7)), 'hora_madrugada'] = 1
# MAÑANA de 07 a 11
eventos['hora_mañana'] = 0
eventos.loc[((eventos.hora > 6) & (eventos.hora < 12)), 'hora_mañana'] = 1
# ALMUERZO de 12 a 13
eventos['hora_almuerzo'] = 0
eventos.loc[((eventos.hora > 11) & (eventos.hora < 14)), 'hora_almuerzo'] = 1
# TARDE de 14 a 18
eventos['hora_tarde'] = 0
eventos.loc[((eventos.hora > 13) & (eventos.hora < 19)), 'hora_tarde'] = 1
# NOCHE de 19 a 23
eventos['hora_noche'] = 0
eventos.loc[((eventos.hora > 18) & (eventos.hora < 24)), 'hora_noche'] = 1
# TRANSFORMAMOS EN CATEGÓRICAS EL DÍA DE LA SEMANA Y EL MES.
eventos['diasemana'] = eventos['diasemana'].astype('category')
eventos['mesMayus'] = eventos['mesMayus'].astype('category')

In [6]:
eventos.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2341681 entries, 1507286 to 1504503
Data columns (total 34 columns):
timestamp                   datetime64[ns]
event                       category
person                      category
url                         object
sku                         float64
model                       category
condition                   category
storage                     category
color                       category
skus                        object
search_term                 object
staticpage                  object
campaign_source             object
search_engine               category
channel                     category
new_vs_returning            category
city                        category
region                      category
country                     category
device_type                 category
screen_resolution           category
operating_system_version    category
browser_version             category
mes                         int64
d

In [7]:
eventos.rename(columns={'staticpage': 'Genstatpage'}, inplace=True)

In [8]:
# COLUMNAS DONDE POR CADA REGISTRO SABEMOS QUE TENEMOS UN VALOR (SIEMPRE PRESENTES)
dummies = pd.get_dummies(eventos['diasemana'], drop_first=False)
eventos = pd.concat([eventos, dummies], axis=1)
dummies = pd.get_dummies(eventos['mesMayus'], drop_first=False)
eventos = pd.concat([eventos, dummies], axis=1)
dummies = pd.get_dummies(eventos['event'], drop_first=False)
eventos = pd.concat([eventos, dummies], axis=1)

In [9]:
## ESTAS COLUMNAS NO APARECEN SIEMPRE, PUESTO QUE SOLO APARECEN SEGÚN EL TIPO DE EVENTO.
dummies = pd.get_dummies(eventos['color'], drop_first=False)
eventos = pd.concat([eventos, dummies], axis=1)
dummies = pd.get_dummies(eventos['model'], drop_first=False)
eventos = pd.concat([eventos, dummies], axis=1)
dummies = pd.get_dummies(eventos['condition'], drop_first=False)
eventos = pd.concat([eventos, dummies], axis=1)
dummies = pd.get_dummies(eventos['storage'], drop_first=False)
eventos = pd.concat([eventos, dummies], axis=1)

In [10]:
dummies = ''
eventos.rename(columns={'generic listing': 'geneList', 'staticpage': 'statpage', 'staticpage': 'SP'}, inplace=True)

In [23]:
eventos_filtrados = ''

# VOY A TRABAJAR CON UN CASO  TESTIGO.
pd.options.display.max_columns = 350

#eventos = eventos[(eventos.person == 'db2c4d27')]
eventos_filtrados = eventos.iloc[0:1000, 0:150] 
eventos_filtrados.head(3)

#eventos_filtrados.info()

timestamp         event    person  url     sku  \
1507286 2018-05-17 12:27:47      checkout  0008ed71  NaN  3372.0   
2336760 2018-05-17 13:44:59  visited site  0008ed71  NaN     NaN   
1507716 2018-05-17 13:45:00      checkout  0008ed71  NaN  8247.0   

                          model  condition storage           color skus  \
1507286  Samsung Galaxy S6 Flat  Muito Bom    32GB         Dourado  NaN   
2336760                     NaN        NaN     NaN             NaN  NaN   
1507716               iPhone SE        Bom    64GB  Cinza espacial  NaN   

        search_term Genstatpage campaign_source search_engine   channel  \
1507286         NaN         NaN             NaN           NaN       NaN   
2336760         NaN         NaN             NaN           NaN  Referral   
1507716         NaN         NaN             NaN           NaN       NaN   

        new_vs_returning     city   region country device_type  \
1507286              NaN      NaN      NaN     NaN         NaN   
2336760              New  Unknown  Unknown  Brazil    Computer   
1507716              NaN      NaN      NaN     NaN         NaN   

        screen_resolution operating_system_version browser_version  mes  dia  \
1507286               NaN                      NaN             NaN    5   17   
2336760         1920x1080              Windows 10      Chrome 66.0    5   17   
1507716               NaN                      NaN             NaN    5   17   

         hora diasemana  finde mesMayus  hora_madrugada  hora_mañana  \
1507286    12    jueves      0     mayo               0            0   
2336760    13    jueves      0     mayo               0            0   
1507716    13    jueves      0     mayo               0            0   

         hora_almuerzo  hora_tarde  hora_noche  domingo  jueves  lunes  \
1507286              1           0           0        0       1      0   
2336760              1           0           0        0       1      0   
1507716              1           0           0        0       1      0   

         martes  miercoles  sabado  viernes  abril  enero  febrero  marzo  \
1507286       0          0       0        0      0      0        0      0   
2336760       0          0       0        0      0      0        0      0   
1507716       0          0       0        0      0      0        0      0   

         mayo  ad campaign hit  brand listing  checkout  conversion  geneList  \
1507286     1                0              0         1           0         0   
2336760     1                0              0         0           0         0   
1507716     1                0              0         1           0         0   

         lead  search engine hit  searched products  SP  viewed product  \
1507286     0                  0                  0   0               0   
2336760     0                  0                  0   0               0   
1507716     0                  0                  0   0               0   

         visited site  Amarelo  Ametista  Azul  Azul Escuro  Azul Safira  \
1507286             0        0         0     0            0            0   
2336760             1        0         0     0            0            0   
1507716             0        0         0     0            0            0   

         Azul Topázio  Bambu  Black Piano  Branco  Branco Azul  \
1507286             0      0            0       0            0   
2336760             0      0            0       0            0   
1507716             0      0            0       0            0   

         Branco Azul Navy  Branco Bambu  Branco Cabernet  Branco Dourado  \
1507286                 0             0                0               0   
2336760                 0             0                0               0   
1507716                 0             0                0               0   

         Branco Framboesa  Branco Pink  Branco Verde  Branco Vermelho  \
1507286                 0            0             0                0   
2336760        

In [12]:
#eventos_agrupados = eventos_agrupados[(eventos_agrupados.person == 'db2c4d27')]
#eventos_agrupados.head()

In [24]:
columnas_filtrar = list(eventos_filtrados.select_dtypes(include=['int','float64','uint8']).columns)

eventos_agrupados = ''
asd = ''

columnas_filtrar.remove('sku')
columnas_filtrar.append('person')
asd = eventos_filtrados.loc[:, eventos_filtrados.columns.isin(columnas_filtrar)]
columnas_filtrar.remove('person')

#asd.head(5)
#asd.info()

eventos_agrupados = asd.groupby('person')[columnas_filtrar].mean().reset_index()
#eventos_agrupados = eventos_agrupados[(eventos_agrupados.dia > 0)]
#eventos_agrupados.head(15)

#asd.head()
#grouped_df = eventos.groupby('person').mean().reset_index()
#entrenar = pd.](grouped_df)

### =======================================================================
### ENTRENAMIENTO Y PREDICCIÓN.
### =======================================================================

In [16]:
## OBTENEMOS TODA LA INFORMACIÓN DEL SET DE ENTRENAMIENTO.
training = ''
train_completo = ''
training = pd.read_csv('labels_training_set.csv', encoding = 'utf-8')

train_completo = pd.merge(training, eventos_agrupados, on='person', how='left')
train_completo.dropna(subset=['person']) 
train_completo.head(20)

person  label  mes    dia       hora  finde  hora_madrugada  \
0   0566e9c1      0  5.0  23.75  15.147059    0.0        0.088235   
1   6ec7ee77      0  NaN    NaN        NaN    NaN             NaN   
2   abe7a2fb      0  NaN    NaN        NaN    NaN             NaN   
3   34728364      0  NaN    NaN        NaN    NaN             NaN   
4   87ed62de      0  NaN    NaN        NaN    NaN             NaN   
5   db2c4d27      1  NaN    NaN        NaN    NaN             NaN   
6   cde431db      0  NaN    NaN        NaN    NaN             NaN   
7   be65035b      0  NaN    NaN        NaN    NaN             NaN   
8   a4178891      0  NaN    NaN        NaN    NaN             NaN   
9   d066f64c      0  NaN    NaN        NaN    NaN             NaN   
10  47a783b9      0  NaN    NaN        NaN    NaN             NaN   
11  7fc00648      0  NaN    NaN        NaN    NaN             NaN   
12  ce16abb3      0  NaN    NaN        NaN    NaN             NaN   
13  4b38d082      0  NaN    NaN        NaN    NaN             NaN   
14  0566e256      0  5.0  17.00  20.000000    0.0        0.000000   
15  e0ffa75e      0  NaN    NaN        NaN    NaN             NaN   
16  79ed8b5b      0  NaN    NaN        NaN    NaN             NaN   
17  20f4c917      0  NaN    NaN        NaN    NaN             NaN   
18  c4af15f2      0  NaN    NaN        NaN    NaN             NaN   
19  de1a55e7      0  NaN    NaN        NaN    NaN             NaN   

    hora_mañana  hora_almuerzo  hora_tarde  hora_noche   domingo    jueves  \
0      0.117647       0.014706    0.705882    0.073529  0.044118  0.235294   
1           NaN            NaN         NaN         NaN       NaN       NaN   
2           NaN            NaN         NaN         NaN       NaN       NaN   
3           NaN            NaN         NaN         NaN       NaN       NaN   
4           NaN            NaN         NaN         NaN       NaN       NaN   
5           NaN            NaN         NaN         NaN       NaN       NaN   
6           NaN            NaN         NaN         NaN       NaN       NaN   
7           NaN            NaN         NaN         NaN       NaN       NaN   
8           NaN            NaN         NaN         NaN       NaN       NaN   
9           NaN            NaN         NaN         NaN       NaN       NaN   
10          NaN            NaN         NaN         NaN       NaN       NaN   
11          NaN            NaN         NaN         NaN       NaN       NaN   
12          NaN            NaN         NaN         NaN       NaN       NaN   
13          NaN            NaN         NaN         NaN       NaN       NaN   
14     0.000000       0.000000    0.000000    1.000000  0.000000  1.000000   
15          NaN            NaN         NaN         NaN       NaN       NaN   
16          NaN            NaN         NaN         NaN       NaN       NaN   
17          NaN            NaN         NaN         NaN       NaN       NaN   
18          NaN            NaN         NaN         NaN       NaN       NaN   
19          NaN            NaN         NaN         NaN       NaN       NaN   

       lunes    martes  miercoles    sabado   viernes  abril  enero  febrero  \
0   0.014706  0.397059       0.25  0.029412  0.029412    0.0    0.0      0.0   
1        NaN       NaN        NaN       NaN       NaN    NaN    NaN      NaN   
2        NaN       NaN        NaN       NaN       NaN    NaN    NaN      NaN   
3        NaN       NaN        NaN       NaN       NaN    NaN    NaN      NaN   
4        NaN       NaN        NaN       NaN       NaN    NaN    NaN      NaN   
5        NaN       NaN        NaN       NaN       NaN    NaN    NaN      NaN   
6        NaN       NaN        NaN       NaN       NaN    NaN    NaN      NaN   
7        NaN       NaN        NaN       NaN       NaN    NaN    NaN      NaN   
8        NaN       NaN        NaN       NaN       NaN    NaN    NaN      NaN   
9        NaN       NaN        NaN       NaN       NaN    NaN    NaN      NaN   
10       NaN       NaN        NaN    

In [14]:
training = ''

In [15]:
y = pd.factorize(train_completo['label'])[0]
train_completo = train_completo[columnas_filtrar]
# VER COMO OBTENER LAS COLUMNAS ESPECÍFICAS QUE QUEREMOS TRABAJAR.
features = train_completo.columns

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 7: ordinal not in range(128)

In [15]:
y

array([0, 0, 0, ..., 0, 0, 0])

In [16]:
# Creamos un clasificador con Random Forest..
clf = RandomForestClassifier(n_jobs=2, random_state=0)
# Entrenamos.
clf.fit(train_completo[features], y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=2,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [17]:
# Predecimos.
eventos_agrupados['label'] = 0
clf.predict(eventos_agrupados[features])

array([0, 0, 0, ..., 0, 0, 0])

In [18]:
# REVISAR. todos dan iguales.
prueba = clf.predict_proba(eventos_agrupados[features])[0:10000]

In [19]:
y = np.unique(prueba)

In [20]:
y

array([0.        , 0.00909091, 0.01111111, 0.01666667, 0.02159091,
       0.025     , 0.02857143, 0.03      , 0.03333333, 0.04      ,
       0.04242424, 0.05      , 0.05975758, 0.06      , 0.06042769,
       0.06333333, 0.06611111, 0.06666667, 0.075     , 0.08      ,
       0.08147547, 0.08333333, 0.09166667, 0.09666667, 0.1       ,
       0.10833333, 0.11      , 0.11666667, 0.11666667, 0.125     ,
       0.12666667, 0.13      , 0.13333333, 0.135     , 0.14      ,
       0.15      , 0.15714286, 0.16      , 0.16666667, 0.175     ,
       0.1752381 , 0.18      , 0.18333333, 0.18333333, 0.18557692,
       0.18666667, 0.18897547, 0.19333333, 0.195     , 0.2       ,
       0.2       , 0.20833333, 0.21      , 0.22111111, 0.2275    ,
       0.22857143, 0.23047619, 0.23214286, 0.25      , 0.25166667,
       0.275     , 0.28833333, 0.29666667, 0.3       , 0.32      ,
       0.33333333, 0.335     , 0.34      , 0.35      , 0.35666667,
       0.3572619 , 0.35833333, 0.36666667, 0.36857143, 0.4    

In [21]:
prueba

array([[1. , 0. ],
       [0.9, 0.1],
       [0.8, 0.2],
       ...,
       [0.9, 0.1],
       [1. , 0. ],
       [1. , 0. ]])